In [60]:
# -*- coding: utf-8 -*-
import numpy as np
  
def subtracao_linhas(linha, ab):
    for x in range(ab.shape[1]):
        if ab[x,linha] != 0 and not np.array_equal(ab[linha],ab[x]) and x > linha:
                ab[x] = ab[x] - ab[linha]*ab[x,linha]    
    return ab
            
def divisao_pivo(linha,ab,det):
    if ab[linha,linha] != 1 and ab[linha,linha] != 0:
        det *= ab[linha,linha]
        ab[linha] = ab[linha]*(1/ab[linha,linha])
    return det,ab

def matriz_cofatora(matriz):
    n = matriz.shape[0]
    cofatores = np.zeros_like(matriz, dtype=float)
    for i in range(n):
        for j in range(n):
            submatriz = matriz[np.arange(n) != i][:, np.arange(n) != j]
            cofatores[i, j] = ((-1) ** (i + j)) * np.linalg.det(submatriz)
    adj = cofatores.T
    
    return adj




def main(A):
    
    ab = A
    matriz = []
    det = 1

    adj_AB = matriz_cofatora(ab)
    # pesquisa todas as linhas com o primiro pivor 
    for x in range(ab.shape[1]):
        if ab[x,0] == 1:
            matriz.append(x)

    # garante que o primeiro lemento é um pivor 
    if ab[0,0] != 1 and matriz:
        ab[0], ab[matriz[0]] = ab[matriz[0]].copy(), ab[0].copy()
        det*=-1

    shape = ab.shape[1]

    for x in range(0,int(shape)-1,1):
        ab = subtracao_linhas(x, ab)
        det,ab = divisao_pivo(x+1, ab,det)
        
    print("\nMatriz Escalonada de A|B:")
    print(np.round(ab, decimals=4))
    print("\nMatriz Adjunta de A|B:")
    print(adj_AB)
    print("\nMatriz transposta de A|B:")
    print(np.round(adj_AB*(1/det), decimals=4))
    print("\nDeterminante pelo metodo de Gauss-Jordan da matriz A|B:",round(det))
  
    

matriz = np.array([[1,10,4,-3,-1,5],[2,2,0,4,6,-14],[3,-1,-1,-1,10,7],[13,-11,5,4,-3,0],[5,-4,-4,3,-1,0],[0,0,6,9,1,-5]],dtype = float)
main(matriz)



Matriz Escalonada de A|B:
[[  1.      10.       4.      -3.      -1.       5.    ]
 [ -0.       1.       0.4444  -0.5556  -0.4444   1.3333]
 [  0.       0.       1.     -11.8571  -1.      42.8571]
 [  0.       0.       0.       1.      -0.246   -3.6458]
 [ -0.      -0.      -0.      -0.       1.      -0.1416]
 [  0.       0.       0.       0.       0.       1.    ]]

Matriz Adjunta de A|B:
[[ 103168.   61360.    9360.   67184.  101504.  -55536.]
 [ 138456.   35790.  -14790.  -52362.  103008.   17538.]
 [   7520.  -10360.    5880.   86920. -226880.   44760.]
 [  11992.  -52610.   13290.  -68794.  189536.  177906.]
 [ -32088.   47250.  122310.   -8694.  -63264.    6846.]
 [  24192.  -97680.   55440.  -21264.   56256.   48336.]]

Matriz transposta de A|B:
[[ 0.0631  0.0375  0.0057  0.0411  0.0621 -0.034 ]
 [ 0.0847  0.0219 -0.009  -0.032   0.063   0.0107]
 [ 0.0046 -0.0063  0.0036  0.0532 -0.1388  0.0274]
 [ 0.0073 -0.0322  0.0081 -0.0421  0.1159  0.1088]
 [-0.0196  0.0289  0.0748 -0.005

In [67]:
# -*- coding: utf-8 -*-
import numpy as np

    
def subtracao_linhas(linha, ab):
   
   
        for x in range(ab.shape[1]):
            if ab[x,linha] != 0 and not np.array_equal(ab[linha],ab[x]) and x > linha:
                    ab[x] = ab[x] - ab[linha]*ab[x,linha]    
        return ab
            
def divisao_pivo(linha,ab):

    if int(ab.shape[1]-1) == linha:
        return ab
    else:
        if ab[linha,linha] != 1 and ab[linha,linha] != 0:
            ab[linha] = ab[linha]*(1/ab[linha,linha])
        return ab


def main(A):
    ab = A
    matriz = []
    

    # pesquisa todas as linhas com o primiro pivor 
    for x in range(ab.shape[1]):
        if ab[x,0] == 1:
            matriz.append(x)

    # garante que o primeiro lemento é um pivor 
    if ab[0,0] != 1 and matriz:
        ab[0], ab[matriz[0]] = ab[matriz[0]].copy(), ab[0].copy()

    shape = ab.shape[1]

    for x in range(0,int(shape)-1,1):
        ab = subtracao_linhas(x, ab)
        ab = divisao_pivo(x+1, ab)


   
    #ab[5,4] = 1
    print(np.round(ab, decimals=4))
    if np.all(ab[ab.shape[0]-1, :-1] == 0) and ab[ab.shape[0]-1,ab.shape[1]-1] !=0:
        print("\nPela última linha é possível perceber que \033[91m não existe solução \033[0m.")
    else:
        print("\nPela última linha é possível perceber que \033[92mexiste solução\033[0m.")


matriz = np.array([[1,10,4,-3,-1,5],[2,2,0,4,6,-14],[3,-1,-1,-1,10,7],[13,-11,5,4,-3,0],[5,-4,-4,3,-1,0],[0,0,6,9,1,-5]],dtype = float)
main(matriz)


[[  1.      10.       4.      -3.      -1.       5.    ]
 [ -0.       1.       0.4444  -0.5556  -0.4444   1.3333]
 [  0.       0.       1.     -11.8571  -1.      42.8571]
 [  0.       0.       0.       1.      -0.246   -3.6458]
 [ -0.      -0.      -0.      -0.       1.      -0.1416]
 [  0.       0.       0.       0.       0.      33.8232]]

Pela última linha é possível perceber que  não existe solução .
